DROP TABLE adresy CASCADE CONSTRAINTS;
DROP TABLE aplikacje CASCADE CONSTRAINTS;
DROP TABLE historie_studentow CASCADE CONSTRAINTS;
DROP TABLE instytuty CASCADE CONSTRAINTS;
DROP TABLE kandydaci CASCADE CONSTRAINTS;
DROP TABLE kierunki CASCADE CONSTRAINTS;
DROP TABLE pracownicy CASCADE CONSTRAINTS;
DROP TABLE pracownicy_administracyjni CASCADE CONSTRAINTS;
DROP TABLE prowadzacy CASCADE CONSTRAINTS;
DROP TABLE przedmioty CASCADE CONSTRAINTS;
DROP TABLE przypisy_prow_do_real CASCADE CONSTRAINTS;
DROP TABLE przypisy_przed_do_kier CASCADE CONSTRAINTS;
DROP TABLE przypisy_stud_do_real CASCADE CONSTRAINTS;
DROP TABLE realizacje_przedmiotow CASCADE CONSTRAINTS;
DROP TABLE rejestracje CASCADE CONSTRAINTS;
DROP TABLE semestry CASCADE CONSTRAINTS;
DROP TABLE studenci CASCADE CONSTRAINTS;

DROP SEQUENCE przypis_pr_seq;
DROP SEQUENCE aplikacja_seq;
DROP SEQUENCE historia_seq;

-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2021-01-26 20:12:01 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE adresy (
    id_adresu          INTEGER NOT NULL,
    ulica              VARCHAR2(30) NOT NULL,
    numer_mieszkania   INTEGER NOT NULL,
    kod_pocztowy       VARCHAR2(10) NOT NULL,
    miejscowosc        VARCHAR2(60) NOT NULL,
    wojewodztwo        VARCHAR2(40) NOT NULL,
    kraj               VARCHAR2(40) NOT NULL
);

ALTER TABLE adresy ADD CONSTRAINT adres_pk PRIMARY KEY ( id_adresu );

CREATE TABLE aplikacje (
    id_aplikacji       INTEGER NOT NULL,
    id_kandydata       INTEGER NOT NULL,
    id_kierunku        INTEGER NOT NULL,
    numer_semestru     VARCHAR2(3) NOT NULL,
    data_dodania       DATE NOT NULL,
    data_wygasniecia   DATE NOT NULL
);

ALTER TABLE aplikacje ADD CONSTRAINT aplikacja_pk PRIMARY KEY ( id_aplikacji );

CREATE TABLE historie_studentow (
    id_historii                INTEGER NOT NULL,
    data_rozpoczecia_studiow   DATE NOT NULL,
    stan                       VARCHAR2(20) NOT NULL,
    data_usuniecia             DATE NOT NULL,
    numer_albumu               INTEGER NOT NULL,
    imie                       VARCHAR2(30) NOT NULL,
    nazwisko                   VARCHAR2(30) NOT NULL,
    pesel                      NUMBER(11) NOT NULL,
    email                      VARCHAR2(40),
    telefon                    NUMBER(9),
    id_kierunku                INTEGER NOT NULL,
    id_adresu                  INTEGER NOT NULL
);

ALTER TABLE historie_studentow ADD CONSTRAINT historia_studenta_pk PRIMARY KEY ( id_historii );

ALTER TABLE historie_studentow ADD CONSTRAINT historia_numer_albumu_un UNIQUE ( numer_albumu );

ALTER TABLE historie_studentow ADD CONSTRAINT historia_pesel_un UNIQUE ( pesel );

CREATE TABLE instytuty (
    id_instytutu   INTEGER NOT NULL,
    nazwa          VARCHAR2(30) NOT NULL,
    email          VARCHAR2(40),
    telefon        NUMBER,
    id_adresu      INTEGER NOT NULL
);

ALTER TABLE instytuty ADD CONSTRAINT instytut_pk PRIMARY KEY ( id_instytutu );

ALTER TABLE instytuty ADD CONSTRAINT instytut_nazwa_un UNIQUE ( nazwa );

CREATE TABLE kandydaci (
    id_kandydata          INTEGER NOT NULL,
    imie                  VARCHAR2(30) NOT NULL,
    nazwisko              VARCHAR2(30) NOT NULL,
    pesel                 NUMBER(11) NOT NULL,
    email                 VARCHAR2(40),
    telefon               NUMBER(9),
    punkty_rekrutacyjne   NUMBER(5, 2),
    id_adresu             INTEGER NOT NULL
);

ALTER TABLE kandydaci ADD CONSTRAINT kandydat_pk PRIMARY KEY ( id_kandydata );

ALTER TABLE kandydaci ADD CONSTRAINT kandydat_pesel_un UNIQUE ( pesel );

CREATE TABLE kierunki (
    id_kierunku                   INTEGER NOT NULL,
    nazwa                         VARCHAR2(30) NOT NULL,
    limit_miejsc                  INTEGER,
    data_rozpoczecia_rekrutacji   DATE,
    data_zakonczenia_rekrutacji   DATE
);

ALTER TABLE kierunki ADD CONSTRAINT kierunek_pk PRIMARY KEY ( id_kierunku );

ALTER TABLE kierunki ADD CONSTRAINT kierunek_nazwa_un UNIQUE ( nazwa );

CREATE TABLE pracownicy (
    id_pracownika   INTEGER NOT NULL,
    selektor        VARCHAR2(30) NOT NULL,
    imie            VARCHAR2(30) NOT NULL,
    nazwisko        VARCHAR2(30) NOT NULL,
    pesel           NUMBER(11) NOT NULL,
    email           VARCHAR2(40),
    telefon         NUMBER(9),
    id_adresu       INTEGER NOT NULL
);

ALTER TABLE pracownicy ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_pracownika );

ALTER TABLE pracownicy ADD CONSTRAINT pracownik_pesel_un UNIQUE ( pesel );

CREATE TABLE pracownicy_administracyjni (
    id_pracownika        INTEGER NOT NULL,
    przyjmowane_sprawy   VARCHAR2(50)
);

ALTER TABLE pracownicy_administracyjni ADD CONSTRAINT pracownik_administracyjny_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE prowadzacy (
    id_pracownika      INTEGER NOT NULL,
    typ_prowadzacego   VARCHAR2(30) NOT NULL,
    id_instytutu       INTEGER NOT NULL
);

ALTER TABLE prowadzacy ADD CONSTRAINT prowadzacy_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE przedmioty (
    id_przedmiotu    INTEGER NOT NULL,
    kod_przedmiotu   VARCHAR2(5) NOT NULL,
    nazwa            VARCHAR2(40) NOT NULL
);

ALTER TABLE przedmioty ADD CONSTRAINT przedmiot_pk PRIMARY KEY ( id_przedmiotu );

ALTER TABLE przedmioty ADD CONSTRAINT przedmiot_kod_przedmiotu_un UNIQUE ( kod_przedmiotu );

CREATE TABLE przypisy_prow_do_real (
    id_przypisu     INTEGER NOT NULL,
    id_pracownika   INTEGER NOT NULL,
    id_realizacji   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL,
    czy_kierownik   CHAR(1) NOT NULL
);

ALTER TABLE przypisy_prow_do_real ADD CONSTRAINT przypis_prow_do_real_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE przypisy_przed_do_kier (
    id_przypisu     INTEGER NOT NULL,
    id_kierunku     INTEGER NOT NULL,
    id_przedmiotu   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL
);

ALTER TABLE przypisy_przed_do_kier ADD CONSTRAINT przypis_przed_do_kier_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE przypisy_stud_do_real (
    id_przypisu     INTEGER NOT NULL,
    id_studenta     INTEGER NOT NULL,
    id_realizacji   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL
);

ALTER TABLE przypisy_stud_do_real ADD CONSTRAINT przypis_stud_do_real_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE realizacje_przedmiotow (
    id_realizacji    INTEGER NOT NULL,
    id_pracownika    INTEGER NOT NULL,
    numer_semestru   VARCHAR2(3) NOT NULL,
    id_przedmiotu    INTEGER NOT NULL
);

ALTER TABLE realizacje_przedmiotow ADD CONSTRAINT realizacja_przedmiotu_pk PRIMARY KEY ( id_realizacji );

CREATE TABLE rejestracje (
    id_rejestracji     INTEGER NOT NULL,
    id_studenta        INTEGER NOT NULL,
    id_realizacji      INTEGER NOT NULL,
    numer_semestru     VARCHAR2(3) NOT NULL,
    data_dodania       DATE NOT NULL,
    data_wygasniecia   DATE NOT NULL
);

ALTER TABLE rejestracje ADD CONSTRAINT rejestracja_pk PRIMARY KEY ( id_rejestracji );

CREATE TABLE semestry (
    numer_semestru VARCHAR2(3) NOT NULL
);

ALTER TABLE semestry ADD CONSTRAINT semestr_pk PRIMARY KEY ( numer_semestru );

CREATE TABLE studenci (
    id_studenta    INTEGER NOT NULL,
    numer_albumu   INTEGER NOT NULL,
    imie           VARCHAR2(30) NOT NULL,
    nazwisko       VARCHAR2(30) NOT NULL,
    pesel          NUMBER(11) NOT NULL,
    email          VARCHAR2(40),
    telefon        NUMBER(9),
    id_kierunku    INTEGER NOT NULL,
    id_adresu      INTEGER NOT NULL,
    id_historii    INTEGER NOT NULL
);

CREATE UNIQUE INDEX student__idx ON
    studenci (
        id_historii
    ASC );

ALTER TABLE studenci ADD CONSTRAINT student_pk PRIMARY KEY ( id_studenta );

ALTER TABLE studenci ADD CONSTRAINT student_pesel_un UNIQUE ( pesel );

ALTER TABLE studenci ADD CONSTRAINT student_numer_albumu_un UNIQUE ( numer_albumu );

ALTER TABLE aplikacje
    ADD CONSTRAINT aplikacja_kandydat_fk FOREIGN KEY ( id_kandydata )
        REFERENCES kandydaci ( id_kandydata );

ALTER TABLE aplikacje
    ADD CONSTRAINT aplikacja_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunki ( id_kierunku );

ALTER TABLE aplikacje
    ADD CONSTRAINT aplikacja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestry ( numer_semestru );

ALTER TABLE instytuty
    ADD CONSTRAINT instytut_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adresy ( id_adresu );

ALTER TABLE kandydaci
    ADD CONSTRAINT kandydat_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adresy ( id_adresu );

ALTER TABLE pracownicy_administracyjni
    ADD CONSTRAINT pracownik_adm_pracownik_fk FOREIGN KEY ( id_pracownika )
        REFERENCES pracownicy ( id_pracownika );

ALTER TABLE pracownicy
    ADD CONSTRAINT pracownik_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adresy ( id_adresu );

ALTER TABLE przypisy_prow_do_real
    ADD CONSTRAINT prow_do_real_prowadzacy_fk FOREIGN KEY ( id_pracownika )
        REFERENCES prowadzacy ( id_pracownika );

ALTER TABLE przypisy_prow_do_real
    ADD CONSTRAINT prow_do_real_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacje_przedmiotow ( id_realizacji );

ALTER TABLE prowadzacy
    ADD CONSTRAINT prowadzacy_instytut_fk FOREIGN KEY ( id_instytutu )
        REFERENCES instytuty ( id_instytutu );

ALTER TABLE prowadzacy
    ADD CONSTRAINT prowadzacy_pracownik_fk FOREIGN KEY ( id_pracownika )
        REFERENCES pracownicy ( id_pracownika );

ALTER TABLE przypisy_przed_do_kier
    ADD CONSTRAINT przed_do_kier_przedmiot_fk FOREIGN KEY ( id_przedmiotu )
        REFERENCES przedmioty ( id_przedmiotu );

ALTER TABLE przypisy_przed_do_kier
    ADD CONSTRAINT przed_do_kieru_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunki ( id_kierunku );

ALTER TABLE realizacje_przedmiotow
    ADD CONSTRAINT realizacja_prowadzacy_fk FOREIGN KEY ( id_pracownika )
        REFERENCES prowadzacy ( id_pracownika );

ALTER TABLE realizacje_przedmiotow
    ADD CONSTRAINT realizacja_przedmiot_fk FOREIGN KEY ( id_przedmiotu )
        REFERENCES przedmioty ( id_przedmiotu );

ALTER TABLE realizacje_przedmiotow
    ADD CONSTRAINT realizacja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestry ( numer_semestru );

ALTER TABLE rejestracje
    ADD CONSTRAINT rejestracja_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacje_przedmiotow ( id_realizacji );

ALTER TABLE rejestracje
    ADD CONSTRAINT rejestracja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestry ( numer_semestru );

ALTER TABLE rejestracje
    ADD CONSTRAINT rejestracja_student_fk FOREIGN KEY ( id_studenta )
        REFERENCES studenci ( id_studenta );

ALTER TABLE przypisy_stud_do_real
    ADD CONSTRAINT stud_do_real_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacje_przedmiotow ( id_realizacji );

ALTER TABLE przypisy_stud_do_real
    ADD CONSTRAINT stud_do_real_student_fk FOREIGN KEY ( id_studenta )
        REFERENCES studenci ( id_studenta );

ALTER TABLE studenci
    ADD CONSTRAINT student_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adresy ( id_adresu );

ALTER TABLE studenci
    ADD CONSTRAINT student_historia_studenta_fk FOREIGN KEY ( id_historii )
        REFERENCES historie_studentow ( id_historii );

ALTER TABLE studenci
    ADD CONSTRAINT student_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunki ( id_kierunku );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             1
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
ALTER TABLE Pracownicy
    ADD CONSTRAINT Selektor_check2
    CHECK (Selektor IN ('Pracownik administracyjny', 'Prowadzacy'));

CREATE SEQUENCE przypis_pr_seq
START WITH 10000 
INCREMENT BY 1
MINVALUE 10000 MAXVALUE 99999
CYCLE;

CREATE SEQUENCE aplikacja_seq
START WITH 10000 
INCREMENT BY 1
MINVALUE 10000 MAXVALUE 99999
CYCLE;