-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2021-01-12 02:51:12 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE adres (
    id_adresu          INTEGER NOT NULL,
    ulica              VARCHAR2(30) NOT NULL,
    numer_mieszkania   INTEGER NOT NULL,
    kod_pocztowy       VARCHAR2(10) NOT NULL,
    miejscowosc        VARCHAR2(60) NOT NULL,
    wojewodztwo        VARCHAR2(40) NOT NULL,
    kraj               VARCHAR2(40) NOT NULL
);

ALTER TABLE adres ADD CONSTRAINT adres_pk PRIMARY KEY ( id_adresu );

CREATE TABLE aplikacja (
    id_aplikacji       INTEGER NOT NULL,
    id_studenta        INTEGER NOT NULL,
    id_kierunku        INTEGER NOT NULL,
    numer_semestru     INTEGER NOT NULL,
    data_dodania       DATE NOT NULL,
    data_wygasniecia   DATE NOT NULL
);

ALTER TABLE aplikacja ADD CONSTRAINT aplikacja_pk PRIMARY KEY ( id_aplikacji );

CREATE TABLE historia_studenta (
    id_historii                INTEGER NOT NULL,
    data_rozpoczecia_studiow   DATE NOT NULL,
    stan                       VARCHAR2(20) NOT NULL,
    data_usuniecia             DATE NOT NULL,
    numer_albumu               INTEGER NOT NULL,
    imie                       VARCHAR2(30) NOT NULL,
    nazwisko                   VARCHAR2(30) NOT NULL,
    pesel                      NUMBER(11) NOT NULL,
    email                      VARCHAR2(40),
    telefon                    NUMBER(9),
    id_kierunku                INTEGER NOT NULL,
    id_adresu                  INTEGER NOT NULL
);

ALTER TABLE historia_studenta ADD CONSTRAINT historia_studenta_pk PRIMARY KEY ( id_historii );

ALTER TABLE historia_studenta ADD CONSTRAINT historia_numer_albumu_un UNIQUE ( numer_albumu );

ALTER TABLE historia_studenta ADD CONSTRAINT historia_pesel_un UNIQUE ( pesel );

CREATE TABLE instytut (
    id_instytutu   INTEGER NOT NULL,
    nazwa          VARCHAR2(30) NOT NULL,
    email          NUMBER,
    telefon        NUMBER,
    id_adresu      INTEGER NOT NULL
);

ALTER TABLE instytut ADD CONSTRAINT instytut_pk PRIMARY KEY ( id_instytutu );

ALTER TABLE instytut ADD CONSTRAINT instytut_nazwa_un UNIQUE ( nazwa );

CREATE TABLE kandydat (
    id_studenta           INTEGER NOT NULL,
    imie                  VARCHAR2(30) NOT NULL,
    nazwisko              VARCHAR2(30) NOT NULL,
    pesel                 NUMBER(11) NOT NULL,
    email                 VARCHAR2(40),
    telefon               NUMBER(9),
    punkty_rekrutacyjne   NUMBER(5, 2),
    id_adresu             INTEGER NOT NULL
);

ALTER TABLE kandydat ADD CONSTRAINT kandydat_pk PRIMARY KEY ( id_studenta );

ALTER TABLE kandydat ADD CONSTRAINT kandydat_pesel_un UNIQUE ( pesel );

CREATE TABLE kierunek (
    id_kierunku                   INTEGER NOT NULL,
    nazwa                         VARCHAR2(30) NOT NULL,
    limit_miejsc                  INTEGER,
    data_rozpoczecia_rekrutacji   DATE,
    data_zakonczenia_rekrutacji   DATE
);

ALTER TABLE kierunek ADD CONSTRAINT kierunek_pk PRIMARY KEY ( id_kierunku );

ALTER TABLE kierunek ADD CONSTRAINT kierunek_nazwa_un UNIQUE ( nazwa );

CREATE TABLE pracownik (
    id_pracownika   INTEGER NOT NULL,
    selektor        VARCHAR2(30) NOT NULL,
    imie            VARCHAR2(30) NOT NULL,
    nazwisko        VARCHAR2(30) NOT NULL,
    pesel           NUMBER(11) NOT NULL,
    email           VARCHAR2(40),
    telefon         NUMBER(9),
    id_adresu       INTEGER NOT NULL
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_pracownika );

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pesel_un UNIQUE ( pesel );

CREATE TABLE pracownik_administracyjny (
    id_pracownika INTEGER NOT NULL
);

ALTER TABLE pracownik_administracyjny ADD CONSTRAINT pracownik_administracyjny_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE prowadzacy (
    id_pracownika      INTEGER NOT NULL,
    typ_prowadzacego   VARCHAR2(30) NOT NULL,
    id_instytutu       INTEGER NOT NULL
);

ALTER TABLE prowadzacy ADD CONSTRAINT prowadzacy_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE przedmiot (
    id_przedmiotu    INTEGER NOT NULL,
    kod_przedmiotu   VARCHAR2(5) NOT NULL,
    nazwa            VARCHAR2(30) NOT NULL
);

ALTER TABLE przedmiot ADD CONSTRAINT przedmiot_pk PRIMARY KEY ( id_przedmiotu );

ALTER TABLE przedmiot ADD CONSTRAINT przedmiot_kod_przedmiotu_un UNIQUE ( kod_przedmiotu );

CREATE TABLE przypis_prow_do_real (
    id_przypisu     INTEGER NOT NULL,
    id_pracownika   INTEGER NOT NULL,
    id_realizacji   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL,
    czy_kierownik   CHAR(1) NOT NULL
);

ALTER TABLE przypis_prow_do_real ADD CONSTRAINT przypis_prow_do_real_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE przypis_przed_do_kier (
    id_przypisu     INTEGER NOT NULL,
    id_kierunku     INTEGER NOT NULL,
    id_przedmiotu   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL
);

ALTER TABLE przypis_przed_do_kier ADD CONSTRAINT przypis_przed_do_kier_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE przypis_stud_do_real (
    id_przypisu     INTEGER NOT NULL,
    id_studenta     INTEGER NOT NULL,
    id_realizacji   INTEGER NOT NULL,
    data_dodania    DATE NOT NULL
);

ALTER TABLE przypis_stud_do_real ADD CONSTRAINT przypis_stud_do_real_pk PRIMARY KEY ( id_przypisu );

CREATE TABLE realizacja_przedmiotu (
    id_realizacji    INTEGER NOT NULL,
    id_pracownika    INTEGER NOT NULL,
    numer_semestru   INTEGER NOT NULL,
    id_przedmiotu    INTEGER NOT NULL
);

ALTER TABLE realizacja_przedmiotu ADD CONSTRAINT realizacja_przedmiotu_pk PRIMARY KEY ( id_realizacji );

CREATE TABLE rejestracja (
    id_rejestracji     INTEGER NOT NULL,
    id_studenta        INTEGER NOT NULL,
    id_realizacji      INTEGER NOT NULL,
    numer_semestru     INTEGER NOT NULL,
    data_dodania       DATE NOT NULL,
    data_wygasniecia   DATE NOT NULL
);

ALTER TABLE rejestracja ADD CONSTRAINT rejestracja_pk PRIMARY KEY ( id_rejestracji );

CREATE TABLE semestr (
    numer_semestru INTEGER NOT NULL
);

ALTER TABLE semestr ADD CONSTRAINT semestr_pk PRIMARY KEY ( numer_semestru );

CREATE TABLE student (
    id_studenta    INTEGER NOT NULL,
    numer_albumu   INTEGER NOT NULL,
    imie           VARCHAR2(30) NOT NULL,
    nazwisko       VARCHAR2(30) NOT NULL,
    pesel          NUMBER(11) NOT NULL,
    email          VARCHAR2(40),
    telefon        NUMBER(9),
    id_kierunku    INTEGER NOT NULL,
    id_adresu      INTEGER NOT NULL,
    id_historii    INTEGER NOT NULL
);

CREATE UNIQUE INDEX student__idx ON
    student (
        id_historii
    ASC );

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( id_studenta );

ALTER TABLE student ADD CONSTRAINT student_numer_albumu_un UNIQUE ( numer_albumu );

ALTER TABLE student ADD CONSTRAINT student_pesel_un UNIQUE ( pesel );

ALTER TABLE aplikacja
    ADD CONSTRAINT aplikacja_kandydat_fk FOREIGN KEY ( id_studenta )
        REFERENCES kandydat ( id_studenta );

ALTER TABLE aplikacja
    ADD CONSTRAINT aplikacja_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunek ( id_kierunku );

ALTER TABLE aplikacja
    ADD CONSTRAINT aplikacja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestr ( numer_semestru );

ALTER TABLE instytut
    ADD CONSTRAINT instytut_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adres ( id_adresu );

ALTER TABLE kandydat
    ADD CONSTRAINT kandydat_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adres ( id_adresu );

ALTER TABLE pracownik_administracyjny
    ADD CONSTRAINT pracownik_adm_pracownik_fk FOREIGN KEY ( id_pracownika )
        REFERENCES pracownik ( id_pracownika );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adres ( id_adresu );

ALTER TABLE przypis_prow_do_real
    ADD CONSTRAINT prow_do_real_prowadzacy_fk FOREIGN KEY ( id_pracownika )
        REFERENCES prowadzacy ( id_pracownika );

ALTER TABLE przypis_prow_do_real
    ADD CONSTRAINT prow_do_real_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacja_przedmiotu ( id_realizacji );

ALTER TABLE prowadzacy
    ADD CONSTRAINT prowadzacy_instytut_fk FOREIGN KEY ( id_instytutu )
        REFERENCES instytut ( id_instytutu );

ALTER TABLE prowadzacy
    ADD CONSTRAINT prowadzacy_pracownik_fk FOREIGN KEY ( id_pracownika )
        REFERENCES pracownik ( id_pracownika );

ALTER TABLE przypis_przed_do_kier
    ADD CONSTRAINT przed_do_kier_przedmiot_fk FOREIGN KEY ( id_przedmiotu )
        REFERENCES przedmiot ( id_przedmiotu );

ALTER TABLE przypis_przed_do_kier
    ADD CONSTRAINT przed_do_kieru_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunek ( id_kierunku );

ALTER TABLE realizacja_przedmiotu
    ADD CONSTRAINT realizacja_prowadzacy_fk FOREIGN KEY ( id_pracownika )
        REFERENCES prowadzacy ( id_pracownika );

ALTER TABLE realizacja_przedmiotu
    ADD CONSTRAINT realizacja_przedmiot_fk FOREIGN KEY ( id_przedmiotu )
        REFERENCES przedmiot ( id_przedmiotu );

ALTER TABLE realizacja_przedmiotu
    ADD CONSTRAINT realizacja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestr ( numer_semestru );

ALTER TABLE rejestracja
    ADD CONSTRAINT rejestracja_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacja_przedmiotu ( id_realizacji );

ALTER TABLE rejestracja
    ADD CONSTRAINT rejestracja_semestr_fk FOREIGN KEY ( numer_semestru )
        REFERENCES semestr ( numer_semestru );

ALTER TABLE rejestracja
    ADD CONSTRAINT rejestracja_student_fk FOREIGN KEY ( id_studenta )
        REFERENCES student ( id_studenta );

ALTER TABLE przypis_stud_do_real
    ADD CONSTRAINT stud_do_real_realizacja_fk FOREIGN KEY ( id_realizacji )
        REFERENCES realizacja_przedmiotu ( id_realizacji );

ALTER TABLE przypis_stud_do_real
    ADD CONSTRAINT stud_do_real_student_fk FOREIGN KEY ( id_studenta )
        REFERENCES student ( id_studenta );

ALTER TABLE student
    ADD CONSTRAINT student_adres_fk FOREIGN KEY ( id_adresu )
        REFERENCES adres ( id_adresu );

ALTER TABLE student
    ADD CONSTRAINT student_historia_studenta_fk FOREIGN KEY ( id_historii )
        REFERENCES historia_studenta ( id_historii );

ALTER TABLE student
    ADD CONSTRAINT student_kierunek_fk FOREIGN KEY ( id_kierunku )
        REFERENCES kierunek ( id_kierunku );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             1
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0